### PR TITLE
Milestone 3: New York Times Article Page

### PR DESCRIPTION
**Pull request by PhillipUg**
## Clone of the New York Times Page

- Developed using HTML & CSS
- Used Grid, float and Flexbox to position the elements on the page
- Used stylelint and W3C html validator to enforce guidelines

### CODE REVIEW

**Comment by OdongAlican** [comment]
Hey @rOluochKe. Thanks a lot for your response. We have fixed the issues that were recommended. Could you please review the project again?

**Comment by OdongAlican** [comment]
Added the .stickler.yml files.

**Comment by uryelah** [comment]
### Code under review by Sarah Chamorro 👩‍🚀

**Comment by uryelah** [comment]
Hello **Phillip Musiime** & **Sunday Odong**, I'm Sarah, your reviewer for this PR  👩‍🚀 

You did a great job completing the required changes from the last review, congrats! 🥇 

**Great job at:**
- using semantic HTML
- removing the `<br>` tags
- positioning the image and text at 'Theory of Inflation' area
- paying attention to text size and color

### Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------

### Optional changes
**(That can improve your project)**

### Touch-ups!

- [ ]  [OPTIONAL] The right buttons at the right have their text wrapping. Please find a way to fix that. 

Screenshot_2020-03-02 New York Times Article Page


Tip: check the CSS `white-space` property
 
- [ ]  [OPTIONAL] Your read me title looks wrong, maybe you can review [how to link in markdown.](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links)
Screenshot_2020-03-02 OdongAlican Newyork-times-article-page

-------

**Keep being awesome devs and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by OdongAlican** [comment]
Thanks a lot @uryelah We will definitely fix that.

**Pull request merged**
